### ISSUE TITLE
How to get landmarks? and Detect single face in each frame?

### ISSUE THREAD

**Issue by abdalazizrashid** [jackweiwang/Android-FaceDetection-UltraNet-MNN#1]

**Comment by jackweiwang** [comment]
This project does not contain landmarks,  you can used retinaNet or mtcnn.
`ultra ->detect(srcmatimg, face_info);`
Detect face and save to face_info.

**Comment by abdalazizrashid** [comment]
Ok, what about detecting a single face instead of multiple faces?
