### ISSUE TITLE
我编译过不了，你是怎么编译的？需要什么依赖？

### ISSUE THREAD

**Issue by 394781865** [jackweiwang/Android-FaceDetection-UltraNet-MNN#10]
CMakeLists.txt中36行find_library(log-lib log); 41行MNN_CL; 45行 z。分别是什么意思，你能解释一下吗？我刚接触这个不太懂。

**Comment by 394781865** [comment]
我是在ubuntu下编译的，下载了NDK并在~/.bashrc 配置了环境变量：export ANDROID_NDK=/home/cli/project/android-ndk-r21

**Comment by YAwei666** [comment]
我也编译不了，用android studio没法编译啊
