### ISSUE TITLE
Can this model get more facial information from pictures?

### ISSUE THREAD

**Issue by BlueBlueSkyZZ** [jackweiwang/Android-FaceDetection-UltraNet-MNN#13]
The original detection result is the bbox position (x1, y1, x2, y2), located in line 99 of "Ultra_jni.cpp":
```
allfaceInfo[4*i+1] = face_info[i].x1;//left
allfaceInfo[4*i+2] = face_info[i].y1;//top
allfaceInfo[4*i+3] = face_info[i].x2;//right
allfaceInfo[4*i+4] = face_info[i].y2;//bottom
```
But I also want to get facial point detection results, such as eyes, nose, mouse position...
Can the model obtain the information?
If possible, how to modify the cpp file to obtain the information.

**Comment by jackweiwang** [comment]
#1
