### ISSUE TITLE
A problem occurred configuring project ':app'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by YAwei666** [jackweiwang/Android-FaceDetection-UltraNet-MNN#19]
do you encounter this problem? how to solve this? thank you

**Comment by saikirantokala** [comment]
add "ndk.dir" in local.properties file

and in app build.gradle defaultConfig, add ndkVersion. (ndkVersion '22.0.7026061')

**Comment by jackweiwang** [comment]
close the issue
