### ISSUE TITLE
RFB量化模型检测没有效果

### ISSUE THREAD

**Issue by xiaoranchenwai** [jackweiwang/Android-FaceDetection-UltraNet-MNN#2]
使用RFB量化模型测试的时候检测框基本没有效果，我想问下您有试过量化模型吗

**Comment by jackweiwang** [comment]
多谢你的提醒， 量化模型确实有问题， 我这边一直没机会修改。

**Comment by xiaoranchenwai** [comment]
> 多谢你的提醒， 量化模型确实有问题， 我这边一直没机会修改。

我也在找原因，用原始的代码，linux下是没有问题的，但是android下好像就是不行

**Comment by jackweiwang** [comment]
> > 多谢你的提醒， 量化模型确实有问题， 我这边一直没机会修改。
> 
> 我也在找原因，用原始的代码，linux下是没有问题的，但是android下好像就是不行

可能是mnn在安卓下输出的问题， 我抽空换个新版本试一试

**Comment by jackweiwang** [comment]
量化模型可以使用
暂时可以将MNN_FORWARD_OPENCL 改成MNN_FORWARD_CPU
具体原因参考这里
https://github.com/alibaba/MNN/issues/167#issuecomment-511777282
