### ISSUE TITLE
Sync报错问题

### ISSUE THREAD

**Issue by thgpddl** [jackweiwang/Android-FaceDetection-UltraNet-MNN#23]
1、当我在Windows使用AndroidStudio打开该项目是，会出现“java.lang.NullPointerException (no error message)”的报错
2、我尝试将project中app的build.gradle中的:
```
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
```
注释掉后再Sync就能正常，但是build的apk在手机上运行是无法进入的，直接闪退
3、目前我还没有找到解决的办法，请问可能的解决办法有哪些？

**Comment by jackweiwang** [comment]
1.是否确认过版本。
2.可以尝试原作者提供的非量化模型。
本项目有段时间没更新 最好使用最新的mnn替换掉我的部分结构
