### ISSUE TITLE
我从ocrlitemnn中把mnn模型拿过来，为啥crnn不出结果呢？

### ISSUE THREAD

**Issue by tomjerrygithub** [jackweiwang/Android-FaceDetection-UltraNet-MNN#25]
我从ocrlitemnn中把mnn模型拿过来，为啥crnn不出结果呢？
https://github.com/thomaszheng/OcrLiteMnn
模型和 libmnn.so 有强匹配关系吗？

**Comment by jackweiwang** [comment]
建议你使用最新的mnn，这个版本太低了，有问题很正常。
